### ISSUE TITLE
trigger processing after receiving an event

### ISSUE THREAD

**Issue by chbrandt** [lpsinger/pygcn#1]
Hi. I have pygcn listening for (vo)events. Everything works fine. What I want to do is to trigger a script (parse the votable and so on) whenever I/pygcn receive an event. Would you have any tip for me on how to best accomplish that?
Thanks.

**Comment by lpsinger** [comment]
Yes! Write a handler function. It takes two arguments: the payload XML as a string, and the root object of the parsed document tree. Then just pass your handler to the `listen()` function.

```python
from gcn import listen

host = ...
port = ...

def process_gcn(payload, root):
    # do work here...

listen(host=host, port=port, handler=process_gcn)
```
