### ISSUE TITLE
No handlers could be found for logger "gcn.listen"

### ISSUE THREAD

**Issue by martinberoiz** [lpsinger/pygcn#2]
Hello Leo,

I updated pygcn (great software btw) and it throws this error message as soon as it starts:

    No handlers could be found for logger "gcn.listen"

I try it with this minimal example with pygcn freshly installed:

    import gcn
    def hello():
        print("Hello!")
    if __name__ == "__main__":
        gcn.listen(port=1234, handler=hello)

Is it just me? Can you reproduce?
Thanks!

**Comment by lpsinger** [comment]
Thank you!

Ah, that error message is referring to [Python logging handlers](https://docs.python.org/2/library/logging.handlers.html), not GCN handlers. It's nothing to worry about.
