### ISSUE TITLE
Importing gcn not working in script. Works in Jupyter notebook

### ISSUE THREAD

**Issue by uzzielperez** [lpsinger/pygcn#3]
Hi, 

I was wondering why I get the following error when running my python script
```
    import gcn
ModuleNotFoundError: No module named 'gcn'.

```
There is no trouble when I import in a Jupyter notebook. 
Please let me know if you have any idea why this is. 

Thank you in advance! 

Uzzie

**Comment by uzzielperez** [comment]
Hi, just in case someone finds this useful, I'm writing my solution. The python script was ran with a different python version that the jupyter python kernel was using. 

To check the python version used by the kernel
```bash
cat /Users/up/Library/Jupyter/kernels/python3/kernel.json 
```
In my case the right python was /Users/up/miniconda3/bin/python and I've just set an alias condapython for it. The pip version that downloaded pygcn is associated with this python.

Cheers, 
Uzzie

**Comment by lpsinger** [comment]
Thanks!
