### ISSUE TITLE
Threading support

### ISSUE THREAD

**Issue by dmopalmer** [lpsinger/pygcn#7]
I need to do threading (e.g. one thread waits for the VO Event, other threads run the telescope).

I have submitted a pull request with my implementation for this.  I have only tested it with the threading API, but the multiprocessing and asyncio APIs should work transparently with this code.

Test added for the queue handler; README.md gives a usage example; command line routine serves as more complete example; PEP-8; Travis gives a green check.

**Comment by lpsinger** [comment]
Hi @dmopalmer. I'm just going to close this issue so that we can keep the discussion in one place on #6.
